CREATE TABLE IF NOT EXISTS {full_table_name} (
    match_id TEXT,
    ingest_date TEXT,
    ingested_at TIMESTAMPTZ,
    character_name TEXT,
    account_id TEXT,
    team_id INTEGER,
    character_health DOUBLE PRECISION,
    character_location_x DOUBLE PRECISION,
    character_location_y DOUBLE PRECISION,
    character_location_z DOUBLE PRECISION,
    zone TEXT,
    seat_index INTEGER,
    ride_distance DOUBLE PRECISION,
    max_speed DOUBLE PRECISION,
    vehicle_type TEXT,
    vehicle_id TEXT,
    vehicle_seat_index INTEGER,
    vehicle_health_percent DOUBLE PRECISION,
    vehicle_fuel_percent DOUBLE PRECISION,
    vehicle_altitude_abs DOUBLE PRECISION,
    vehicle_altitude_rel DOUBLE PRECISION,
    vehicle_velocity DOUBLE PRECISION,
    is_engine_on BOOLEAN,
    is_in_water_volume BOOLEAN,
    is_wheels_in_air BOOLEAN,
    vehicle_location_x DOUBLE PRECISION,
    vehicle_location_y DOUBLE PRECISION,
    vehicle_location_z DOUBLE PRECISION
);