CREATE TABLE IF NOT EXISTS {full_table_name} (
    match_id TEXT,
    ingest_date TEXT,
    ingested_at TIMESTAMPTZ,
    attack_id BIGINT,
    attacker_name TEXT,
    attacker_account_id TEXT,
    attacker_team_id INTEGER,
    attacker_health DOUBLE PRECISION,
    attacker_location_x DOUBLE PRECISION,
    attacker_location_y DOUBLE PRECISION,
    attacker_location_z DOUBLE PRECISION,
    attacker_zone TEXT,
    victim_name TEXT,
    victim_account_id TEXT,
    victim_team_id INTEGER,
    victim_health DOUBLE PRECISION,
    victim_location_x DOUBLE PRECISION,
    victim_location_y DOUBLE PRECISION,
    victim_location_z DOUBLE PRECISION,
    victim_zone TEXT,
    damage_type_category TEXT,
    damage_reason TEXT,
    damage DOUBLE PRECISION,
    damage_causer_name TEXT,
    is_through_penetrable_wall BOOLEAN,
    is_game DOUBLE PRECISION
);